; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-atom]
platform = espressif32@6.2.0
board = m5stack-atom
framework = arduino
board_build.partitions = no_ota.csv
upload_speed = 1500000
monitor_speed = 115200
lib_deps = 
  m5stack/M5Unified @ 0.1.16
  earlephilhower/ESP8266Audio @ ^1.9.7
  bblanchon/ArduinoJson @ ^6
;  meganetaaan/M5Stack-Avatar@^0.9.2 ;ミニマル版をlibに同梱
  ESP32WebServer ; Add for Web Setting
  horihiro/esp8266-google-tts @ 1.1.0 ;Google tts

[env:m5stack-atoms3]
platform = espressif32@6.2.0
board = m5stack-atoms3
framework = arduino
board_build.partitions = no_ota.csv
upload_speed = 1500000
monitor_speed = 115200
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.psram_type = opi
build_flags = 
  -DATOMS3R
  -DBOARD_HAS_PSRAM
lib_deps = 
  m5stack/M5Unified @ 0.1.16
  earlephilhower/ESP8266Audio @ ^1.9.7
  bblanchon/ArduinoJson @ ^6
;  meganetaaan/M5Stack-Avatar@^0.9.2 ;ミニマル版をlibに同梱
  ESP32WebServer ; Add for Web Setting
  horihiro/esp8266-google-tts @ 1.1.0 ;Google tts